import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = new Inter({
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} bg-gray-100 text-gray-900 font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
